let productsDB = [
  {
    id: 1,
    title: "crystal uhd",
    price: 250.0,
    size: "large",
    imageURL: "images/product-6.webp",
    qty: 1,
  },
  {
    id: 2,
    title: "4k lcd",
    price: 250.0,
    size: "large",
    imageURL: "images/product-5.png",
    qty: 1,
  },
  {
    id: 3,
    title: "euphona",
    price: 250.0,
    size: "large",
    imageURL: "images/product-1.webp",
    qty: 1,
  },
  {
    id: 4,
    title: "chrome",
    price: 250.0,
    size: "large",
    imageURL: "images/product-7.webp",
    qty: 1,
  },
  {
    id: 5,
    title: "jaguar",
    price: 250.0,
    size: "large",
    imageURL: "images/product-2.png",
    qty: 1,
  },
  {
    id: 6,
    title: "victorius",
    price: 250.0,
    size: "large",
    imageURL: "images/product-3.webp",
    qty: 1,
  },
  {
    id: 7,
    title: "if",
    price: 250.0,
    size: "large",
    imageURL: "images/product-4.webp",
    qty: 1,
  },
  {
    id: 8,
    title: "kcaroule",
    price: 250.0,
    size: "large",
    imageURL: "images/product-9.webp",
    qty: 1,
  },
  {
    id: 9,
    title: "data show",
    price: 250.0,
    size: "large",
    imageURL: "images/product-10.webp",
    qty: 1,
  },
  {
    id: 10,
    title: "i shadow",
    price: 250.0,
    size: "large",
    imageURL: "images/product-12.webp",
    qty: 1,
  },
  {
    id: 11,
    title: "floor clean",
    price: 250.0,
    size: "large",
    imageURL: "images/product-13.webp",
    qty: 1,
  },
  {
    id: 12,
    title: "shoes",
    price: 250.0,
    size: "large",
    imageURL: "images/product-14.webp",
    qty: 1,
  },
  {
    id: 13,
    title: "shoes",
    price: 250.0,
    size: "large",
    imageURL: "images/product-33.webp",
    qty: 1,
  },
  {
    id: 14,
    title: "shoes",
    price: 250.0,
    size: "large",
    imageURL: "images/product-34.png",
    qty: 1,
  },
  {
    id: 15,
    title: "shoes",
    price: 250.0,
    size: "large",
    imageURL: "images/product-32.webp",
    qty: 1,
  },
  {
    id: 16,
    title: "shoes",
    price: 250.0,
    size: "large",
    imageURL: "images/product-31.webp",
    qty: 1,
  },
  {
    id: 17,
    title: "shoes",
    price: 250.0,
    size: "large",
    imageURL: "images/product-29.webp",
    qty: 1,
  },
  {
    id: 18,
    title: "shoes",
    price: 250.0,
    size: "large",
    imageURL: "images/product-30.webp",
    qty: 1,
  },
  {
    id: 20,
    title: "dav sat",
    price: 250.0,
    size: "large",
    imageURL: "images/product-37.webp",
    qty: 1,
  },
  {
    id: 21,
    title: "lady speed stick",
    price: 250.0,
    size: "large",
    imageURL: "images/product-18.webp",
    qty: 1,
  },
];

localStorage.setItem("products", JSON.stringify(productsDB));
